apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    # Source: Tail container logs from logging-test namespace
    <source>
      @type tail
      path /var/log/containers/*_logging-test_*.log
      exclude_path ["/var/log/containers/fluentd*.log"]
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%N%:z
      </parse>
    </source>

    # Add Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "#{ENV['KUBERNETES_URL']}"
      verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL']}"
      ca_file "#{ENV['KUBERNETES_CA_FILE']}"
      skip_labels false
      skip_container_metadata false
      skip_master_url false
      skip_namespace_metadata false
    </filter>

    # Filter only logging-test namespace
    <filter kubernetes.**>
      @type grep
      <regexp>
        key $['kubernetes']['namespace_name']
        pattern ^logging-test$
      </regexp>
    </filter>

    # Route AUDIT logs first
    <match kubernetes.**>
      @type rewrite_tag_filter
      <rule>
        key log
        pattern /\[AUDIT\]/
        tag audit.logs
      </rule>
      <rule>
        key log
        pattern /.*/
        tag app.${record['kubernetes']['labels']['app'] || 'unmatched'}
      </rule>
    </match>

    # Output 1: AUDIT logs to audit-trail index
    <match audit.logs>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      user "#{ENV['ELASTICSEARCH_USERNAME']}"
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      scheme "#{ENV['ELASTICSEARCH_SCHEME']}"
      ssl_verify false
      
      index_name audit-trail
      suppress_type_name true
      
      <buffer>
        @type file
        path /var/log/fluentd-buffers/audit
        flush_mode interval
        flush_interval 10s
        retry_max_times 3
        chunk_limit_size 5MB
      </buffer>
    </match>

    # Output 2: App-specific logs to dynamic indices
    <match app.**>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      user "#{ENV['ELASTICSEARCH_USERNAME']}"
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      scheme "#{ENV['ELASTICSEARCH_SCHEME']}"
      ssl_verify false
      
      # Extract app name from tag (everything after "app.")
      index_name ${tag[4..-1]}
      suppress_type_name true
      
      <buffer tag>
        @type file
        path /var/log/fluentd-buffers/apps
        flush_mode interval  
        flush_interval 10s
        retry_max_times 3
        chunk_limit_size 5MB
      </buffer>
    </match>

    # Output 3: Fallback
    <match **>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      user "#{ENV['ELASTICSEARCH_USERNAME']}"
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      scheme "#{ENV['ELASTICSEARCH_SCHEME']}"
      ssl_verify false
      
      index_name unmatched-logs
      suppress_type_name true
      
      <buffer>
        @type file
        path /var/log/fluentd-buffers/fallback
        flush_mode interval
        flush_interval 10s
        retry_max_times 3
        chunk_limit_size 5MB
      </buffer>
    </match>