apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    # Multi-Namespace Configuration with CENTRALIZED Audit Trail
    # All AUDIT logs go to a single centralized index
    
    # Source: Tail container logs from multiple namespaces
    <source>
      @type tail
      path /var/log/containers/*_logging-test_*.log,/var/log/containers/*_production_*.log,/var/log/containers/*_staging_*.log,/var/log/containers/*_development_*.log
      exclude_path ["/var/log/containers/fluentd*.log"]
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%N%:z
      </parse>
    </source>

    # Add Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "#{ENV['KUBERNETES_URL']}"
      verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL']}"
      ca_file "#{ENV['KUBERNETES_CA_FILE']}"
      skip_labels false
      skip_container_metadata false
      skip_master_url false
      skip_namespace_metadata false
    </filter>

    # Filter: Allow multiple namespaces
    <filter kubernetes.**>
      @type grep
      <regexp>
        key $['kubernetes']['namespace_name']
        pattern ^(logging-test|production|staging|development)$
      </regexp>
    </filter>

    # Add namespace and app information
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby
      <record>
        namespace_app ${record['kubernetes']['namespace_name']}_${record['kubernetes']['labels']['app'] || 'generic'}
        environment ${record['kubernetes']['namespace_name']}
        @timestamp ${Time.now.strftime('%Y-%m-%dT%H:%M:%S.%3NZ')}
      </record>
    </filter>

    # Parse AUDIT log message into structured fields
    <filter kubernetes.**>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type grok
        grok_pattern \[AUDIT\]\s*user=(?<User>[^,]+),\s*action=(?<Action>[^,]+),\s*project=(?<Project>[^,]+),\s*status=(?<Status>[^,]+),\s*Field=(?<Field>[^,]+),\s*old_value=(?<Old_value>[^,]+),\s*new_value=(?<New_value>.+)
      </parse>
    </filter>

    # Route AUDIT logs and namespace-specific logs
    <match kubernetes.**>
      @type rewrite_tag_filter
      <rule>
        key log
        pattern /\[AUDIT\]/
        tag audit.logs
      </rule>
      <rule>
        key namespace_app
        pattern (.+)
        tag app.${1}
      </rule>
    </match>

    # Output 1: CENTRALIZED AUDIT logs to single index
    <match audit.logs>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      user "#{ENV['ELASTICSEARCH_USERNAME']}"
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      scheme "#{ENV['ELASTICSEARCH_SCHEME']}"
      ssl_verify false
      
      index_name centralized_audit-trail
      suppress_type_name true
      
      <buffer>
        @type file
        path /var/log/fluentd-buffers/centralized-audit
        flush_mode interval
        flush_interval 10s
        retry_max_times 3
        chunk_limit_size 5MB
      </buffer>
    </match>

    # Output 2: App-specific logs with namespace_app format
    <match app.**>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      user "#{ENV['ELASTICSEARCH_USERNAME']}"
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      scheme "#{ENV['ELASTICSEARCH_SCHEME']}"
      ssl_verify false
      
      index_name ${namespace_app}
      suppress_type_name true
      
      <buffer namespace_app>
        @type file
        path /var/log/fluentd-buffers/apps
        flush_mode interval  
        flush_interval 10s
        retry_max_times 3
        chunk_limit_size 5MB
      </buffer>
    </match>

    # Drop Fluentd internal logs
    <match fluent.**>
      @type null
    </match>

    # Output 3: Fallback for any remaining logs
    <match **>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      user "#{ENV['ELASTICSEARCH_USERNAME']}"
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      scheme "#{ENV['ELASTICSEARCH_SCHEME']}"
      ssl_verify false
      
      index_name multi-namespace-generic
      suppress_type_name true
      
      <buffer>
        @type file
        path /var/log/fluentd-buffers/fallback
        flush_mode interval
        flush_interval 10s
        retry_max_times 3
        chunk_limit_size 5MB
      </buffer>
    </match>