apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: logging
data:
  elasticsearch-host: "192.168.1.10"
  elasticsearch-port: "9200"
  elasticsearch-scheme: "http"
  elasticsearch-username: "elastic"
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-creds
  namespace: logging
type: Opaque
data:
  password: Y2hhbmdlbWU=  # changeme (base64 encoded)