---
# Test Deployment 1: Web Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-web-service
  namespace: logging
  labels:
    app: web-service
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
        tier: frontend
    spec:
      containers:
      - name: web-container
        image: busybox:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          counter=1
          while true; do
            echo "[$(date)] WEB-SERVICE: Processing request #$counter"
            echo "[$(date)] WEB-SERVICE: Response sent successfully - ID: $counter"
            echo "[$(date)] WEB-SERVICE: Cache hit ratio: $((counter % 10 + 85))%"
            counter=$((counter + 1))
            sleep 3
          done
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"

---
# Test Deployment 2: API Service  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api-service
  namespace: logging
  labels:
    app: api-service
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
        tier: backend
    spec:
      containers:
      - name: api-container
        image: busybox:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          counter=1
          while true; do
            echo "[$(date)] API-SERVICE: Handling API call #$counter"
            echo "[$(date)] API-SERVICE: Database query executed - Duration: $((counter % 50 + 10))ms"
            echo "[$(date)] API-SERVICE: JSON response generated for request #$counter"
            counter=$((counter + 1))
            sleep 4
          done
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"

---
# Test Deployment 3: Worker Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-worker-service
  namespace: logging
  labels:
    app: worker-service
    tier: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
        tier: processing
    spec:
      containers:
      - name: worker-container
        image: busybox:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          counter=1
          while true; do
            echo "[$(date)] WORKER-SERVICE: Processing background job #$counter"
            echo "[$(date)] WORKER-SERVICE: Task completed successfully - Job ID: $counter"
            echo "[$(date)] WORKER-SERVICE: Queue size: $((counter % 20)) remaining jobs"
            counter=$((counter + 1))
            sleep 5
          done
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
