apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: logging
data:
  elasticsearch-host: 10.0.0.180
  elasticsearch-port: "9200"
  elasticsearch-scheme: https
  elasticsearch-username: elastic