apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config-deployment-based
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      exclude_path ["/var/log/containers/fluentd*.log"]
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%N%:z
      </parse>
    </source>

    # Add Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "https://kubernetes.default.svc:443"
      verify_ssl true
      ca_file "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      skip_labels false
      skip_container_metadata false
      skip_master_url false
      skip_namespace_metadata false
    </filter>

    # Filter to include only specific namespaces
    <filter kubernetes.**>
      @type grep
      <regexp>
        key $.kubernetes.namespace_name
        pattern ^(logging|mon)$
      </regexp>
    </filter>

    # Extract deployment name from pod labels or pod name
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      auto_typecast true
      <record>
        timestamp ${Time.now.strftime('%Y-%m-%dT%H:%M:%S.%3NZ')}
        pod_name ${record["kubernetes"]["pod_name"] || "unknown"}
        namespace ${record["kubernetes"]["namespace_name"] || "unknown"}
        container_name ${record["kubernetes"]["container_name"] || "unknown"}
        host ${record["kubernetes"]["host"] || "unknown"}
        pod_id ${record["kubernetes"]["pod_id"] || "unknown"}
        deployment_name ${begin; labels = record["kubernetes"]["labels"] || {}; pod_name = record["kubernetes"]["pod_name"] || "unknown"; if labels["app"]; labels["app"]; elsif labels["app.kubernetes.io/name"]; labels["app.kubernetes.io/name"]; elsif labels["k8s-app"]; labels["k8s-app"]; elsif pod_name =~ /^(.+)-[0-9a-f]{8,10}-[a-z0-9]{5}$/; $1; elsif pod_name =~ /^(.+)-[0-9]+$/; $1; elsif pod_name =~ /^(.+)-[a-z0-9]{5,}$/; $1; else; pod_name; end; rescue; "unknown"; end}
      </record>
    </filter>

    # Send to Elasticsearch with dynamic index name based on deployment
    <match kubernetes.**>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      scheme "#{ENV['ELASTICSEARCH_SCHEME']}"
      ssl_verify false
      user "#{ENV['ELASTICSEARCH_USERNAME']}"
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"

      # Use deployment name as index prefix
      index_name ${deployment_name}

      # ES 8.x+ settings
      suppress_type_name true

      # Buffer configuration - group by deployment_name
      <buffer deployment_name>
        @type file
        path /var/log/fluentd-buffers/deployment.*.buffer
        flush_mode interval
        flush_interval 10s
        chunk_limit_size 5M
        total_limit_size 500M
        queue_limit_length 8
        overflow_action drop_oldest_chunk
        retry_max_interval 30
        retry_forever false
        retry_max_times 3
      </buffer>

      # Error handling
      <secondary>
        @type file
        path /var/log/fluentd-buffers/failed-records.log
      </secondary>
    </match>