apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config-simple
  namespace: logging
data:
  fluent.conf: |
    <system>
      log_level info
    </system>

    <source>
      @type tail
      path /var/log/containers/audit-test-app*.log
      pos_file /var/log/fluentd-audit.log.pos
      tag audit
      <parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%N%:z
      </parse>
    </source>

    <filter audit>
      @type grep
      <regexp>
        key log
        pattern /\[AUDIT\]/
      </regexp>
    </filter>

    <match audit>
      @type elasticsearch
      @log_level debug
      scheme https
      ssl_verify false
      host 10.0.0.180
      port 9200
      user elastic
      password JlhRQbkK=ljsQZ_imzXV
      index_name auditor
      type_name _doc
      suppress_type_name true
      write_operation index
      <buffer>
        @type memory
        flush_interval 5s
        chunk_limit_size 5M
        queue_limit_length 4
        overflow_action block
      </buffer>
    </match>