apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config-final
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/audit-test-app*.log
      pos_file /var/log/fluentd-audit.log.pos
      tag audit
      <parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%N%:z
      </parse>
    </source>

    <filter audit>
      @type kubernetes_metadata
      @id filter_kube_metadata
      skip_labels true
      skip_container_metadata true
      verify_ssl false
      ca_file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    </filter>

    <filter audit>
      @type grep
      <regexp>
        key log
        pattern /\[AUDIT\]/
      </regexp>
    </filter>

    <filter audit>
      @type record_transformer
      enable_ruby true
      <record>
        @timestamp ${time.strftime("%Y-%m-%dT%H:%M:%S.%3NZ")}
        pod_name ${record["kubernetes"]["pod_name"]}
        namespace ${record["kubernetes"]["namespace_name"]}
        container_name ${record["kubernetes"]["container_name"]}
      </record>
    </filter>

    <match audit>
      @type elasticsearch
      host 10.0.0.180
      port 9200
      scheme https
      ssl_verify false
      user elastic
      password JlhRQbkK=ljsQZ_imzXV
      index_name auditor-2025.06.03
      include_timestamp false
      suppress_type_name true
      <buffer>
        @type memory
        flush_mode immediate
      </buffer>
    </match>