apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      exclude_path ["/var/log/containers/fluentd*.log"]
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type regexp
        expression /^(?<time>.+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$/
        time_format %Y-%m-%dT%H:%M:%S.%N%:z
      </parse>
    </source>

    # Add Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "https://kubernetes.default.svc:443"
      verify_ssl true
      ca_file "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      skip_labels false
      skip_container_metadata false
      skip_master_url false
      skip_namespace_metadata false
    </filter>

    # Filter only audit logs
    <filter kubernetes.**>
      @type grep
      <regexp>
        key log
        pattern /\[AUDIT\]/
      </regexp>
    </filter>

    # Add pod info at top level with safe access
    <filter kubernetes.**>
      @type record_transformer
      enable_ruby true
      <record>
        timestamp ${time.strftime('%Y-%m-%dT%H:%M:%S.%3NZ')}
        pod_name ${record.dig("kubernetes", "pod_name") || "unknown"}
        namespace ${record.dig("kubernetes", "namespace_name") || "unknown"}
        container_name ${record.dig("kubernetes", "container_name") || "unknown"}
        host ${record.dig("kubernetes", "host") || "unknown"}
        pod_id ${record.dig("kubernetes", "pod_id") || "unknown"}
      </record>
    </filter>

    # Send to Elasticsearch
    <match kubernetes.**>
      @type elasticsearch
      host 10.0.0.180
      port 9200
      scheme https
      ssl_verify false
      user elastic
      password JlhRQbkK=ljsQZ_imzXV
      
      # Use a fixed index for now to avoid mapping issues
      index_name auditor-test
      
      # ES 8.x+ settings
      suppress_type_name true
      
      # Buffer configuration
      <buffer>
        @type memory
        flush_mode immediate
        retry_max_times 3
      </buffer>
    </match>