apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: logging
data:
  elasticsearch-host: "172.21.0.1"
  elasticsearch-port: "9200"
  elasticsearch-scheme: "http"
  elasticsearch-username: "elastic"