---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: app
        image: busybox:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo \"$(date) [INFO] api-gateway: request processed path=/api/users status=200\"; sleep 2; echo \"$(date) [WARN] api-gateway: slow query detected duration=850ms\"; sleep 3; echo \"$(date) [ERROR] api-gateway: connection timeout upstream=db\"; sleep 1; done"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-worker
  labels:
    app: jobs-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-worker
  template:
    metadata:
      labels:
        app: jobs-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: app
        image: busybox:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo \"$(date) [INFO] jobs-worker: job started id=job-123\"; sleep 1; echo \"$(date) [INFO] jobs-worker: processing batch size=50\"; sleep 2; echo \"$(date) [WARN] jobs-worker: retrying failed task attempt=2\"; sleep 3; done"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  labels:
    app: audit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: app
        image: busybox:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo \"$(date) [INFO] audit-service: service started\"; sleep 1; echo \"$(date) [AUDIT] user=alice, action=login, project=Ghana, status=success, Field=TPS, old_value=25, new_value=50\"; sleep 2; echo \"$(date) [AUDIT] user=bob, action=delete, project=Nigeria, status=success, Field=Budget, old_value=1000, new_value=0\"; sleep 1; echo \"$(date) [AUDIT] user=charlie, action=update, project=Ghana, status=failed, Field=TPS, old_value=50, new_value=150\"; sleep 2; echo \"$(date) [AUDIT] user=admin, action=create, project=Kenya, status=success, Field=Revenue, old_value=0, new_value=5000\"; sleep 3; done"]